### PR TITLE
feat(frontend)/workflow-list-enhancement

### PR DESCRIPTION
**Pull request by tdari**
This PR will add checkboxes to the workflow list to control workflows by choosing desired workflows. 

Also, #298 will be implemented.

Initial design:

image

### CODE REVIEW

**Comment by vinicvaz** [comment]
This is amazing @tdari ! Will it be multi select? Maybe we can keep at least the run button for a single workflow.

Let me ask you something, do you have an email or linkedin I can contact you?

**Comment by tdari** [comment]
Hey @vinicvaz, yes it will be multi select. Users can select a single workflow to take action but we can add an action menu for every workflow if you prefer that.

**Comment by vinicvaz** [comment]
@tdari Yeah, I asked the run button just to keep things simple to single workflows. The checkboxes are really good for multi select but for quick actions the run button is great. I think we should keep both for run. The others (delete and pause) we can use only checkboxes

**Comment by tdari** [comment]
Hey @vinicvaz, I accidentally closed this PR by renaming the branch can you somehow re-open this so we can keep the history? I couldn't find a way to reopen it. The reopen button is disabled on my screen.

**Comment by vinicvaz** [comment]
@tdari I can't reopen it because there is a force push to the repo. Here is a (old) discussion about 
 this https://github.com/isaacs/github/issues/361#issuecomment-114297034

**Pull request closed without merging**
